image:
  file: .gitpod.Dockerfile
  
task:
  - init: mvn clean install
    command: |
      export HMR_HOST=`gp url 8080`
      mvn clean test -Dwebdriver.chrome.driver=./chromedriver
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8887
    visibility: private
    onOpen: open-browser
