tasks:
  - init: |
      #sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      sudo docker pull registry.gitlab.com/spiculedata/intellij-build-tools:latest
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo chown -R 1000:gitpod .
      sudo chmod g+w -R .
      # Community Edition
      # sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c
      # Ultimate Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/webcrawlerwrapper:/home/projector-user -it registry.gitlab.com/spiculedata/intellij-build-tools:latest
image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8887
    visibility: private
    onOpen: open-browser
