
image: registry.gitlab.com/spiculedata/custom-gitpod-full:latest
tasks:
  - init: |
      git lfs pull
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo docker run --rm -p 8887:8887 -p 8080:8080 -v /workspace/seleniumscripter:/workspace/seleniumscripter -v /workspace/seleniumscripter/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c
      sudo chown -R 1000:1000 seleniumscripter
ports:
  - port: 8080
    visibility: private
  - port: 8887
    visibility: private
