image: registry.gitlab.com/spiculedata/custom-gitpod-full:latest
tasks:
  - init: |
      git lfs pull
      sudo docker pull registry.gitlab.com/spiculedata/intellij-community-build-tools:latest
      #sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      #sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo chown -R 1000:1000 seleniumscripter
      # Community Edition
      sudo docker run --rm -p 8887:8887 -p 8080:8080 -v /workspace/.jetbrains/seleniumscripter:/workspace/seleniumscripter -v /workspace/.jetbrains/seleniumscripter/.jetbrains:/home/projector-user -it registry.gitlab.com/spiculedata/intellij-community-build-tools
      # Ultimate Edition
      #sudo docker run --rm -p 8887:8887 -p 8080:8080 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-u    
ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
  - port: 8080
    visibility: public
    onOpen: open-browser
