tasks:
  - init: sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
    command: |      
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c      
  - init: mvn clean install
    command: |
      export HMR_HOST=`gp url 8080`
      mvn clean test -Dwebdriver.gecko.driver=./geckodriver
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8887
    visibility: private
    onOpen: open-browser
