image:
file: .gitpod.Dockerfile
tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      #sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/seleniumscripter/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c
      # Ultimate Edition
      #sudo docker run --rm -p 8887:8887 -v /workspace/seleniumscripter/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-u
      sudo mv /usr/bin/chromedriver /workspace/seleniumscripter \
      sudo chown root:root /workspace/seleniumscripter/chromedriver \
      sudo chmod +x /workspace/seleniumscripter/chromedriver \
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8887
    visibility: private
    onOpen: open-browser
